### ISSUE TITLE
Does the code works with VGG Image Annotation v2.0.11?

### ISSUE THREAD

**Issue by Genius-farmer** [SriRamGovardhanam/wastedata-multiple-classes#5]
I have been trying to do it on my own custom datasets. However, I have been having issue with VGG Annotator v2.0.10 / v2.0.11.

is there anybody that could advise?

**Comment by SriRamGovardhanam** [comment]
Sorry for the delayed response, I remember it is VGG 2.0
https://www.robots.ox.ac.uk/~vgg/software/via/via-2.0.0.html
